export { default as AddPost } from './AddPost'
export { default as About } from './About'
export { default as Post } from './Post'
export { default as Posts } from './Posts'
export type { PostType } from './Posts'
